<?php $this->partial("public/header") ?>
<div class="am-cf admin-main">
  <!-- sidebar start -->
  <?php $this->partial("public/left") ?>
  <!-- sidebar end -->

  <!-- content start -->
  <div class="admin-content">

    <div class="am-cf am-margin">
      <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">设置APP</strong></div>
    </div>

	<div class="am-g">
      <div class="am-u-md-6 am-cf">
        <div class="am-fl am-cf">
          <div class="am-btn-toolbar am-fl">
            <div class="am-btn-group am-btn-group-xs">
              <a class="am-btn am-btn-default" href="/app/index"><span class="am-icon-mail-reply"></span> 返回</a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="am-g">
      <div class="am-u-sm-12">
      <?php echo $this->tag->form(["app/create","class"=>"am-form am-form-horizontal"]) ?>
      <?php use Phalcon\Tag; ?>

		<?php echo $this->getContent(); ?>
        
          <table class="am-table am-table-bd am-table-striped admin-content-table">
    <tr>
        <td>
            <label for="username">用户名</label>
        </td>
        <td>
            <?php echo $this->tag->textField(array("username", "size" => 30, 'placeholder' => '请输入用户名')) ?>
        </td>
    </tr>

     <tr>
        <td>
            <label for="info">备注</label>
        </td>
        <td>
            <?php echo $this->tag->textArea(array("info", "size" => 50, 'placeholder' => '')) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton(["提交","class"=>"am-btn am-btn-primary"]) ?></td>
    </tr>
</table>
 <?= $this->tag->endForm() ?>
      </div>

  </div>
  <!-- content end -->

</div>
<?php $this->partial("public/footer") ?>