<?php $this->partial("public/header") ?>
<div class="am-cf admin-main">
  <!-- sidebar start -->
  <?php $this->partial("public/left") ?>
  <!-- sidebar end -->

  <style>
  .am-input-group-label{
    line-height: 31px;height:31px;
  }
  </style>
  <!-- content start -->
  <div class="admin-content">

    <div class="am-cf am-margin">
      <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">监控方案管理</strong></div>
    </div>

	<div class="am-g">
      <div class="am-u-md-2 am-cf">
        <div class="am-fl am-cf">
          <div class="am-btn-toolbar am-fl">
            <div class="am-btn-group am-btn-group-xs">
              <a class="am-btn am-btn-default" href="/monitorsolution/new"><span class="am-icon-plus"></span> 新增</a>
            </div>
          </div>
        </div>
      </div>
      
      <?php echo $this->tag->form(array("monitorsolution/index", "autocomplete" => "off","class"=>"am-form")) ?>
      <!--div class="am-u-md-3 am-cf">
        <div class="am-fr">
          <div class="am-input-group am-input-group-sm">
          
            <input type="text" class="am-form-field" name="name" placeholder='请输入方案名称' />
                <span class="am-input-group-btn">
                  <input class="am-btn am-btn-default" type="submit" value="搜索">
                </span>
                
          </div>
        </div>
      </div-->

      <div class="am-u-md-10 am-cf am-fr" style="line-height: 30px">
        <div class="am-input-group am-fr">
          <input class="am-btn am-btn-default" type="submit" value="搜索" style="width:120px; " />
        </div>
        <div class="am-fr">
          <div class="am-input-group am-fr" style="width:270px;margin: 0 20px;">
                <span class="am-input-group-label">方案名</span>
                <input type="text" class="am-form-field" name="name" placeholder="请输入方案名" value="<?php echo $name;?>">
          </div>
        </div>
        <div class="am-fr">
            <div class="am-input-group am-fr" style="width:180px;">
              <span class="am-input-group-label">状态</span>
              <select class="data-am-selected" name="status" >
                <option value='all' <?php if($status == 'all') echo 'selected'?>>全部</option>
                <option value='0' <?php if($status == '0') echo 'selected'?>>禁用</option>
                <option value='1' <?php if($status == '1') echo 'selected'?>>启用</option>
              </select>
          </div>
        </div>
      </div>
      </form>
    </div>

    <div class="am-g">
      <div class="am-u-sm-12 am-scrollable-horizontal">
      <?php use Phalcon\Tag; ?>

		<?php echo $this->getContent(); ?>
        <table class="am-table am-table-bd am-table-striped am-table-compact am-table-hover admin-content-table am-table-bordered ">
          <thead>
          <tr>
            <th width="50">ID</th>
            <th width="90">方案名</th>
            <th width="100">文件传输类型</th>
            <th width="120">远程传输路径</th>
            <th width="160">切片信息汇报地址</th>
            <th width="120">本地存储切片数量</th>
            <th width="50">片长</th>
            <th width="120">创建时间</th>
            <th width="60">状态</th>
            <th width="150">操作</th>
          </tr>
          </thead>
          <tbody>
          <?php foreach ($page->items as $monitorsolution) { ?>
          <tr>
            <td><?php echo $monitorsolution->msid ?></td>
            <td><?php echo $monitorsolution->name ?></td>
            <td><?php  if($monitorsolution->transtype ==1) {echo 'file';}else{ echo 'remote';} ?></td>
            <td><?php echo $monitorsolution->targetpath ?></td>
            <td width="160"><?php echo $monitorsolution->slicereportpath ?></td>
            <td><?php echo $monitorsolution->slicenumber ?></td>
            <td><?php echo $monitorsolution->cliptime ?></td>
            <td><?php echo $monitorsolution->createtime?></td>
            <td><?php  if($monitorsolution->status ==1) {echo '启用';}else{ echo '禁用';} ?></td>

            <td width="150">
              <div class="lszh-inline-block">
                  <?php echo $this->tag->linkTo(array("monitorsolution/view/" . $monitorsolution->msid, "查看")); ?>
                 <?php echo $this->tag->linkTo(array("monitorsolution/edit/" . $monitorsolution->msid, "编辑")); ?>
                 <a href="javascript:void(0);" data-href='/monitorsolution/delete/<?php echo $monitorsolution->msid ?>' class='delete'>删除</a>
              </div>
            </td>
          </tr>
    	  <?php } ?>
          </tbody>
          <tbody>
        </table>
        <br><br><br><br>
        <?php if($page->total_pages > 1){?> 
        <div class="am-cf">
  			<div class="am-fr">
    			<ul class="am-pagination">
    				<li class="am-disabled"><?php echo $page->current, "/", $page->total_pages ?></li>
      				<li><?php echo $this->tag->linkTo("monitorsolution/index?page=1", "首页") ?></li>
      				<li><?php echo $this->tag->linkTo("monitorsolution/index?page=" . $page->before, "上一页") ?></li>
      				<li><?php echo $this->tag->linkTo("monitorsolution/index?page=" . $page->next, "下一页") ?></li>
      				<li><?php echo $this->tag->linkTo("monitorsolution/index?page=" . $page->last, "末页") ?></li>
      				
    			</ul>
  			</div>
		</div>
		<?php }?>
      </div>
    </div>
  </div>
  <!-- content end -->

</div>
<div class="am-modal am-modal-confirm" tabindex="-1" id="my-confirm">
  <div class="am-modal-dialog">
    <div class="am-modal-hd"></div>
    <div class="am-modal-bd">
    </div>
    <div class="am-modal-footer">
      <span class="am-modal-btn" data-am-modal-cancel>取消</span>
      <span class="am-modal-btn" data-am-modal-confirm>确定</span>
    </div>
  </div>
</div>
<?php $this->partial("public/footer") ?>
<script type="text/javascript">
$(function() {
  $('.delete').on('click', function() {
      $('.am-modal-hd').html('删除数据');
      $('.am-modal-bd').html('你确定要删除这条记录吗？');
      var deleteHref = $(this).attr("data-href");
      $('#my-confirm').modal({
        relatedTarget: this,
        onConfirm: function(options) {
          window.location.href = deleteHref;
        },
        // closeOnConfirm: false,
        onCancel: function() {
          return false;
        }
      });
    });

});
</script>