<?php $this->partial("public/header") ?>
<div class="am-cf admin-main">
  <!-- sidebar start -->
  <?php $this->partial("public/left") ?>
  <!-- sidebar end -->

  <!-- content start -->
  <div class="admin-content">

    <div class="am-cf am-margin">
      <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">添加管理员</strong></div>
    </div>

	<div class="am-g">
      <div class="am-u-md-6 am-cf">
        <div class="am-fl am-cf">
          <div class="am-btn-toolbar am-fl">
            <div class="am-btn-group am-btn-group-xs">
              <a class="am-btn am-btn-default" href="/admin/index"><span class="am-icon-mail-reply"></span> 返回</a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="am-g">
      <div class="am-u-sm-12">
      <?php echo $this->tag->form(["admin/create","class"=>"am-form am-form-horizontal lszh-validate"]) ?>
      <?php use Phalcon\Tag; ?>

		<?php echo $this->getContent(); ?>
        
          <table class="am-table am-table-bd am-table-striped admin-content-table">
    <tr>
        <td width="120">
            <label for="username">用户名</label>
        </td>
        <td width="450">
            <div class="am-form-group">
            <?php echo $this->tag->textField(array("username", "size" => 30, 'placeholder' => '请输入用户名',"maxlength"=>"30","class"=>"js-pattern-adminName","required"=>"","data-validation-message" => "请输入用户名（限英文或数字）")) ?>
            </div>
        </td>
        <td><span class="lszh-validate-tip-star">*</span></td>
    </tr>
    <tr>
        <td width="120">
            <label for="password">密码</label>
        </td>
        <td width="450">
            <div class="am-form-group">
            <?php echo $this->tag->passwordField(array("password", "size" => 30,"minlength"=>"4","maxlength"=>"16", 'placeholder' => '请输入密码',"required"=>"","autocomplete"=>"off" ,"data-validation-message" => "请输入密码,4-16位")) ?>
            </div>
        </td>
        <td><span class="lszh-validate-tip-star">*</span></td>
    </tr>
    <tr>
        <td width="120">
            <label for="password">角色</label>
        </td>
        <td width="450">
            <div class="am-form-group">
            <?php echo  $roleid ?>
            </div>
        </td>
        <td></td>
    </tr>
    <tr>
        <td width="120"></td>
        <td width="450"><?php echo $this->tag->submitButton(["提交","class"=>"am-btn am-btn-primary"]) ?></td>
        <td></td>
    </tr>
</table>
 <?= $this->tag->endForm() ?>
      </div>

  </div>
  <!-- content end -->

</div>
<script>
/* 去除chrome自动填充*/
window.onload = function(){
  var username = document.getElementById("username");
  username.value=" ";
  setTimeout(function(){ username.value=""},100);
}
/* 去除chrome自动填充 end*/
</script>
<?php $this->partial("public/footer") ?>