<?php $this->partial("public/header") ?>
<div class="am-cf admin-main">
  <!-- sidebar start -->
  <?php $this->partial("public/left") ?>
  <!-- sidebar end -->

  <!-- content start -->
  <div class="admin-content">

    <div class="am-cf am-margin">
      <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">资源管理</strong></div>
    </div>

	<div class="am-g">
      <div class="am-u-md-9 am-cf">
        <div class="am-fl am-cf">
          <div class="am-btn-toolbar am-fl">
            <div class="am-btn-group am-btn-group-xs">
              <a class="am-btn am-btn-default" href="/resource/new"><span class="am-icon-plus"></span> 新增资源</a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="am-g">
      <div class="am-u-sm-12">
      <?php use Phalcon\Tag; ?>

		<?php echo $this->getContent(); ?>
        <table class="am-table am-table-bd am-table-striped am-table-compact am-table-hover  admin-content-table am-table-bordered">
          <thead>
          <tr class="am-text-nowrap">
            <th width="50">ID</th>
            <th width="120">资源名称</th>
            <th width="120">资源描述</th>
            <th>操作列表</th>
            <th width="160">管理</th>
          </tr>
          </thead>
          <tbody>

          <?php foreach ($allresource as $resouce) { ?>
          <tr>
            <td><?php echo $resouce['resourceid'] ?></td>
            <td style="font-weight: bold;color:#28b779"><?php echo $resouce['name'] ?>  </td>
            <td width="160"> <?php echo $resouce['resourceinfo'] ?></td>
            <td>
               <?php if (isset($resouce['opera'])) { ?>
              <?php foreach ($resouce['opera'] as $opera) { ?>
              <div style="display:inline-block;margin-right:20px;">
              <span style="font-weight: bold;"> <?php echo $opera['name'] ?></span>(<?php echo $opera['operationinfo'] ?>)     [<?php echo $this->tag->linkTo(array("resource/editopera/" . $opera['operationid'], "编辑")); ?>] [<a href="javascript:void(0);" data-href='/resource/deleteopera/<?php echo $opera["operationid"] ?>' class='delete'>删除</a>]
              </div>
              <?php } ?>
              <?php } ?>
                </td>
            <td>
              <?php echo $this->tag->linkTo(array("resource/addopera/" . $resouce['resourceid'], "添加操作")); ?>
              <?php echo $this->tag->linkTo(array("resource/edit/" . $resouce['resourceid'], "编辑")); ?>
              <!--?php echo $this->tag->linkTo(array("resource/delete/" . $resouce['resourceid'], "删除")); ?-->
              <a href="javascript:void(0);" data-href='/resource/delete/<?php echo $resouce["resourceid"] ?>' class='delete'>删除</a>

            </td>
          </tr>
    	  <?php } ?>
          </tbody>
          <tbody>
        </table>

      </div>
    </div>
  </div>
  <!-- content end -->

</div>
<div class="am-modal am-modal-confirm" tabindex="-1" id="my-confirm">
  <div class="am-modal-dialog">
    <div class="am-modal-hd"></div>
    <div class="am-modal-bd">
    </div>
    <div class="am-modal-footer">
      <span class="am-modal-btn" data-am-modal-cancel>取消</span>
      <span class="am-modal-btn" data-am-modal-confirm>确定</span>
    </div>
  </div>
</div>
<?php $this->partial("public/footer") ?>
<script type="text/javascript">
$(function() {
  $('.delete').on('click', function() {
      $('.am-modal-hd').html('删除数据');
      $('.am-modal-bd').html('你确定要删除这条记录吗？');
      var deleteHref = $(this).attr("data-href");
      $('#my-confirm').modal({
        relatedTarget: this,
        onConfirm: function(options) {
          window.location.href = deleteHref;
        },
        // closeOnConfirm: false,
        onCancel: function() {
          return false;
        }
      });
    });

});
</script>