<?php $this->partial("public/header") ?>
<div class="am-cf admin-main">
  <!-- sidebar start -->
  <?php $this->partial("public/left") ?>
  <!-- sidebar end -->

  <!-- content start -->
  <div class="admin-content">

    <div class="am-cf am-margin">
      <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">编辑监控点</strong></div>
    </div>

	<div class="am-g">
      <div class="am-u-md-6 am-cf">
        <div class="am-fl am-cf">
          <div class="am-btn-toolbar am-fl">
            <div class="am-btn-group am-btn-group-xs">
              <a class="am-btn am-btn-default" href="/monitor/index"><span class="am-icon-plus"></span> 返回</a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="am-g">
      <div class="am-u-sm-12">
      <?php echo $this->tag->form(["monitor/save","class"=>"am-form am-form-horizontal"]) ?>
      <?php use Phalcon\Tag; ?>

		<?php echo $this->getContent(); ?>
        
          <table class="am-table am-table-bd am-table-striped admin-content-table">
    <tr>
        <td>
            <label for="mcid">监控分类</label>
        </td>
        <td>
  <?php echo $this->tag->selectStatic(['mcid',$monitorcategory,'','useEmpty'=>true,"emptyText"=>'请选择',"emptyValue"=>'0']) ?>
        </td>
    </tr>
    <tr>
        <td>
            <label for="mname"><span style="color:red;">*</span>名称</label>
        </td>
        <td>
            <?php echo $this->tag->textField(array("mname", "size" => 80, 'placeholder' => '请输入名称')) ?>
        </td>
    </tr>
    <tr>
        <td>
            <label for="msid">监控方案</label>
        </td>
        <td>
  <?php echo $this->tag->selectStatic(['msid',$solutions,'','useEmpty'=>true,"emptyText"=>'请选择',"emptyValue"=>'0']) ?>
        </td>
    </tr>
         
    
    <tr>
        <td>
            <label for="mac">mac地址</label>
        </td>
        <td>
            <?php echo $this->tag->textField(array("mac", "size" => 80, 'placeholder' => '请输入名称')) ?>
        </td>
    </tr>
    <tr>
        <td>
            <label for="soucetype">源地址类型</label>
        </td>
        <td>
  <?php echo $this->tag->selectStatic(['soucetype',$soucetype,'','useEmpty'=>true,"emptyText"=>'请选择',"emptyValue"=>'0']) ?>
        </td>
    </tr>
    <tr>
        <td>
            <label for="sourcepath">源地址</label>
        </td>
        <td>
            <?php echo $this->tag->textField(array("sourcepath", "size" => 80, 'placeholder' => '请输入名称')) ?>
        </td>
    </tr>
    <tr>
        <td>
            <label for="cid">摄像头类型</label>
        </td>
        <td>
  <?php echo $this->tag->selectStatic(['cid',$cameratype,'','useEmpty'=>true,"emptyText"=>'请选择',"emptyValue"=>'0']) ?>
        </td>
    </tr>
    <tr>
        <td>
            <label for="cameraip">摄像头ip</label>
        </td>
        <td>
            <?php echo $this->tag->textField(array("cameraip", "size" => 80, 'placeholder' => '请输入名称')) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("mid") ?></td>
        <td><?php echo $this->tag->submitButton(["设置","class"=>"am-btn am-btn-primary"]) ?></td>
    </tr>
</table>
  </form>
      </div>

  </div>
  <!-- content end -->

</div>
<?php $this->partial("public/footer") ?>