<?php $this->partial("public/header") ?>
<div class="am-cf admin-main">
  <!-- sidebar start -->
  <?php $this->partial("public/left") ?>
  <!-- sidebar end -->

  <style>
  .am-input-group-label{
    line-height: 31px;height:31px;
  }
  </style>
  <!-- content start -->
  <div class="admin-content">

    <div class="am-cf am-margin">
      <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">监控任务管理</strong></div>
    </div>

	<div class="am-g">
      <div class="am-u-md-9 am-cf">
        <div class="am-fl am-cf">
          <div class="am-btn-toolbar am-fl">
            <div class="am-btn-group am-btn-group-xs">
              <!-- <a class="am-btn am-btn-default" href="/monitor/new"><span class="am-icon-plus"></span> 新增</a> -->
            </div>
          </div>
        </div>
      </div>
      
      <?php echo $this->tag->form(array("monitortask/index/".$mid, "autocomplete" => "off","class"=>"am-form")) ?>
      <!-- <div class="am-u-md-3 am-cf">
        <div class="am-fr">
          
          <div class="am-input-group am-input-group-sm">
            <?php echo $this->tag->selectStatic(['mcid',$monitorcategory,'','useEmpty'=>true,"emptyText"=>'请选择分类',"emptyValue"=>'0']) ?>
            <input type="text" class="am-form-field" name="mname" value="<?php echo $mname;?>" placeholder='请输入监控名称'>
                <span class="am-input-group-btn">
                  <input class="am-btn am-btn-default" type="submit" value="搜索">
                </span>
                
          </div>
        </div>
      </div> -->
      <div class="am-u-md-12 am-cf am-fr" style="line-height: 30px"> <!--am-u-md-7-->


        <div class="am-input-group am-fr">

          <input class="am-btn am-btn-default" type="submit" value="搜索" style="width:60px;"/>

        </div>
        <div class="am-fr">
            <div class="am-input-group am-fr" style="width:240px;margin:0 10px;">
              <span class="am-input-group-label">监控名称</span>
              <input type="text" class="am-form-field" name="mname" placeholder="请输入监控名称" value="<?php echo $mname;?>">
            </div>
        </div>
        <div class="am-fr">
              <div class="am-input-group input-group" style="width:220px;">
              <span class="am-input-group-label">监控分类</span>
              <select class="data-am-selected" name="mcid" >
              <option value='0'>请选择</option>
              <?php foreach($monitorcategory as $k=>$v):?>
                <option value='<?php echo $k; ?>' <?php if($k==$mcid) echo 'selected'?>><?php echo $v; ?></option>
              <?php endforeach;?>
              </select>
              </div>
        </div>
        <div class="am-fr">
            <div class="am-input-group input-group" style="width:180px;margin:0 10px;">
              <span class="am-input-group-label">启动状态</span>
              <select class="data-am-selected" name="mtstatus" >
                <option value='100' <?php if(0==$status) echo 'selected'?>>全部</option>
                <option value='1' <?php if(1==$status) echo 'selected'?>>启动进行中</option>
                <option value='2' <?php if(2==$status) echo 'selected'?>>启动成功</option>
                <option value='3' <?php if(3==$status) echo 'selected'?>>停止</option>
              </select>
          </div>
        </div>
        <div class="am-fr">
            <div class="am-input-group input-group" style="width:260px;">
              <span class="am-input-group-label">切片服务器名称</span>
              <select class="data-am-selected" name="ssid" >
                <option value='0'>请选择</option>
                <?php foreach($slicesever as $k=>$v):?>
                  <option value='<?php echo $k; ?>' <?php if($k==$ssid) echo 'selected'?>><?php echo $v; ?></option>
                <?php endforeach;?>
              </select>
            </div>
          </div>
        </div>



      </div>
      </form>
    <div class="am-g">
      <div class="am-u-sm-12">
      <?php use Phalcon\Tag; ?>

		<?php echo $this->getContent(); ?>
        <table class="am-table am-table-bd am-table-striped am-table-compact am-table-hover admin-content-table am-table-bordered">
          <thead>
          <tr>
            <th width="260">任务ID</th>
            <th width="140">监控点名称</th>
            <th width="260">监控点ID</th>
            <th width="120">分类名称</th>
            <th width="140">切片服务器名称</th>
            <th width="120">启动状态</th>
            <th width="120">运行状态码<div class="lszh-validate-tip">
                <span class="am-icon-md am-icon-question-circle-o lszh-validate-tip-icon">
                  <div class="am-comment-main lszh-validate-tip-txt">
                    <div class="am-comment-bd">0:成功<br>304:启动任务源连接失败<br>101:Xml格式错误<br>102:任务已存在<br>203:源接收错误<br>204:源连接错误
                    <br>402:写存储失败<br>403:通知nofify失败</div>
                  </div>
                </span>
            </div></th>
            <th width="140">更新时间</th>
            <th width="140">创建时间</th>
          </tr>
          </thead>
          <tbody>
          <?php foreach ($page->items as $list) { ?>
          <tr>
            <td><?php echo $list->taskid ?></td>
            <td width="140"><?php echo $list->mname ?></td>
            <td><?php echo $list->mid ?></td>
            <td><?php echo $list->categoryname; ?></td>
            <td><?php echo $list->msolutioname; ?></td>
            <td><?php echo $list->status==1?'启动进行中':($list->status==2?'启动成功':'停止'); ?></td>
            <td><?php echo $list->code ?></td>
            <td><?php echo $list->updatetime ?></td>
            <td><?php echo $list->createtime ?></td>
            <!-- <td>
              <?php if($list->status ==1) {echo $this->tag->linkTo(array("monitortask/close/" . $list->mid, "关闭"));}?>
              <!--?php echo $this->tag->linkTo(array("monitortask/delete/" . $list->mid, "删除")); ?>
            </td> -->
          </tr>
    	  <?php } ?>
          </tbody>
          <tbody>
        </table>
        <?php if($page->total_pages > 1){?> 
        <div class="am-cf">
  			<div class="am-fr">
    			<ul class="am-pagination">
    				<li class="am-disabled"><?php echo $page->current, "/", $page->total_pages ?></li>
      				<li><?php echo $this->tag->linkTo("monitortask/index/$mid?page=1", "首页") ?></li>
      				<li><?php echo $this->tag->linkTo("monitortask/index/$mid?page=" . $page->before, "上一页") ?></li>
      				<li><?php echo $this->tag->linkTo("monitortask/index/$mid?page=" . $page->next, "下一页") ?></li>
      				<li><?php echo $this->tag->linkTo("monitortask/index/$mid?page=" . $page->last, "末页") ?></li>
      				
    			</ul>
  			</div>
		</div>
		<?php }?>
      </div>
    </div>
  </div>
  <!-- content end -->

</div>
<?php $this->partial("public/footer") ?>