<?php $this->partial("public/header") ?>
    <div class="am-cf admin-main">
    <!-- sidebar start -->
    <?php $this->partial("public/left") ?>
    <!-- sidebar end -->

    <!-- content start -->
    <div class="admin-content">

        <div class="am-cf am-margin">
            <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">添加系统变量</strong></div>
        </div>

        <div class="am-g">
            <div class="am-u-md-6 am-cf">
                <div class="am-fl am-cf">
                    <div class="am-btn-toolbar am-fl">
                        <div class="am-btn-group am-btn-group-xs">
                            <a class="am-btn am-btn-default" href="/setting/index"><span class="am-icon-mail-reply"></span> 返回</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="am-g">
            <div class="am-u-sm-12">
                <?php echo $this->tag->form(["setting/create","class"=>"am-form am-form-horizontal lszh-validate"]) ?>
                <?php use Phalcon\Tag; ?>

                <?php echo $this->getContent(); ?>

                <table class="am-table am-table-bd am-table-striped admin-content-table">
                    <tr>
                        <td width="140">
                            <label for="name">变量名称</label>
                        </td>
                        <td width="450">
                            <div class="am-form-group">
                                <?php echo $this->tag->textField(array("name", "size" => 50, 'placeholder' => '请输入变量名称',"maxlength"=>"255","minlength"=>"2","class"=>"js-pattern-adminName","required"=>"","data-validation-message" => "请输入变量名（限英文或数字）")) ?>
                            </div>
                        </td>
                        <td><span class="lszh-validate-tip-star">*</span></td>
                    </tr>
                    <tr>
                        <td width="140">
                            <label for="value">变量值</label>
                        </td>
                        <td width="450">
                            <div class="am-form-group">
                                <?php echo $this->tag->textField(array("value", "size" => 100, 'placeholder' => '请输入变量值',"maxlength"=>"255","required"=>"","data-validation-message" => "请输入变量值")) ?>
                            </div>
                        </td>
                        <td><span class="lszh-validate-tip-star">*</span></td>
                    </tr>
                    <tr>
                        <td width="220">
                            <label for="info">备注</label>
                        </td>
                        <td width="450">
                            <?php echo $this->tag->textArea(
                                [
                                    "info",
                                    "",
                                    "cols" => "30",
                                    "rows" => 6,
                                ]
                            ) ?>                  </td>
                        <td> </td>
                    </tr>

                    <tr>
                        <td width="140"></td>
                        <td width="450"><?php echo $this->tag->submitButton(["提交","class"=>"am-btn am-btn-primary"]) ?></td>
                        <td></td>
                    </tr>
                </table>
                <?= $this->tag->endForm() ?>
            </div>

        </div>
        <!-- content end -->

    </div>
<?php $this->partial("public/footer") ?>