<?php $this->partial("public/header") ?>
<div class="am-cf admin-main">
  <!-- sidebar start -->
  <?php $this->partial("public/left") ?>
  <!-- sidebar end -->

  <style>
  .am-input-group-label{
    line-height: 31px;height:31px;
  }
  @media only screen and (max-width: 1340px){
    .am-u-md-11{
      padding:10px;
      width:100%;
    }
    .clearBoth{
      clear:both;
    }
  }
  </style>
  <!-- content start -->
  <div class="admin-content">

    <div class="am-cf am-margin">
      <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">监控点管理</strong></div>
    </div>

	<div class="am-g">
      <div class="am-u-md-1 am-cf">
        <div class="am-fl am-cf">
          <div class="am-btn-toolbar am-fl">
            <div class="am-btn-group am-btn-group-xs">
              <a class="am-btn am-btn-default" href="/monitor/new"><span class="am-icon-plus"></span> 新增</a>
            </div>
          </div>
        </div>
      </div>
      <div class="clearBoth"></div>
      <?php echo $this->tag->form(array("monitor/index", "autocomplete" => "off","class"=>"am-form")) ?>
      <!--div class="am-u-md-3 am-cf">
        <div class="am-fr">
          <div class="am-input-group am-input-group-sm">
            <input type="text" class="am-form-field" name="mname" value="<?php echo $mname?>" placeholder = '请输入监控名称'>
                <span class="am-input-group-btn">
                  <input class="am-btn am-btn-default" type="submit" value="搜索">
                </span>
                
          </div>
        </div>
      </div-->

      <div class="am-u-md-11 am-cf am-fr" style="line-height: 30px">
        <div class="am-input-group am-fr">
            <input class="am-btn am-btn-default" type="submit" value="搜索" style="width:60px;"/>
        </div>
        <div class="am-fr">
            <div class="am-input-group am-fr" style="width:240px;margin:0 10px;">
                  <span class="am-input-group-label">监控名称</span>
                  <input type="text" class="am-form-field" name="mname" placeholder="请输入监控名称" value="<?php echo $mname;?>" />
            </div>
        </div>
        <div class="am-fr">
            <div class="am-input-group input-group" style="width:160px;">
                  <span class="am-input-group-label">状态</span>
                  <select class="data-am-selected" name="mstatus" >
                  <option value='all' <?php if($mstatus == 'all') echo 'selected'?>>全部</option>
                  <option value='0' <?php if($mstatus == '0') echo 'selected'?>>禁用</option>
                  <option value='1' <?php if($mstatus == '1') echo 'selected'?>>启用</option>
                </select>
          </div>
        </div>
        <div class="am-fr">
            <div class="am-input-group input-group" style="width:260px;margin:0 10px;">
                <span class="am-input-group-label">切片服务器</span>
                <select class="data-am-selected" name="ssid" >
                <option value='0'>请选择</option>
                <?php foreach($searchsliceserver as $k=>$v):?>
                  <option value='<?php echo $v->ssid; ?>' <?php if($v->ssid==$ssid) echo 'selected'?>><?php echo $v->ssname; ?></option>
                <?php endforeach;?>
              </select>
            </div>
          </div>
        <div class="am-fr">
            <div class="am-input-group input-group" style="width:180px;">
                <span class="am-input-group-label">监控分类</span>
                <select class="data-am-selected" name="mcid" >
                <option value='0'>请选择</option>
                <?php foreach($searchmonitorcategory as $k=>$v):?>
                  <option value='<?php echo $v->mcid; ?>' <?php if($v->mcid==$mcid) echo 'selected'?>><?php echo $v->categoryname; ?></option>
                <?php endforeach;?>
              </select>
            </div>
          </div>
        </div>
      </form>
      </div>

    <div class="am-g">
      <div style="clear:both"></div>
      <div class="am-u-sm-12">
      <?php use Phalcon\Tag; ?>

		<?php echo $this->getContent(); ?>
          <div class="box" style="padding-bottom: 10px;">
              <input type="button" id="checked" value="批量启用" />
              <input type="button" id="checkeds" value="批量禁用" />

          </div>

          <table class="am-table am-table-bd am-table-striped am-table-compact am-table-hover admin-content-table am-table-bordered ">
          <thead>
          <tr>
            <th width="20"></th>
            <th width="260">ID</th>
            <th width="100">名称</th>
            <th width="100">监控分类</th>
            <th width="70">切片服务器</th>
            <th width="80">摄像头型号</th>
            <th width="200">源地址</th>
            <th width="150">摄像头ip</th>            
            <th width="130">创建时间</th>
            <th width="60">状态</th>
              <th width="40">预览</th>
            <th width="80">管理</th>
          </tr>
          </thead>
          <tbody>
          <?php foreach ($page->items as $list) { ?>
          <tr>
            <td><input type="checkbox" name="items" value="<?php echo $list->mid ?>"  class="checkitem"></td>
            <td width="260"><?php echo $list->mid ?></td>
            <td width="100"><?php echo $list->mname ?></td>
            <td width="100"><?php if(isset($monitorcategory[$list->mcid])) echo $monitorcategory[$list->mcid]->categoryname; ?></td>
            <td width="70"><?php if(isset($solutions[$list->ssid])) echo $solutions[$list->ssid]->ssname; ?></td>
            <td width="80"><?php if(isset($cameratype[$list->cid])) echo $cameratype[$list->cid]->name ?></td>
            <td width="200"><?php echo $list->sourcepath ?></td>
            <td width="150"><?php echo $list->cameraip ?></td>            
            <td width="130"><?php echo $list->createtime ?></td>
            <td width="60"><?php echo $list->mstatus ==1?'正常':'禁用' ?></td>
            <td width="40" align="center"><?php echo $list->mstatus ==1?"
 <img src='/assets/img/play.png' width='20' height='20' data-href=/monitor/openVideo/$list->mid data-am-modal='{target: \"#doc-modal-1\", closeViaDimmer: 0, width: 800, height: 550}' class='openVideo' style='cursor:pointer;'>":'<img src="/assets/img/stop.png" width="20" height="20">' ?></td>
            <td width="80">
              <div class="lszh-inline-block">
              <!--?php if($list->mstatus==1){echo $this->tag->linkTo(array("monitor/updatestatus/" . $list->mid.'/0', "禁用")); }else{echo $this->tag->linkTo(array("monitor/updatestatus/" . $list->mid.'/1', "启用"));}?-->
              <?php if($list->mstatus ==1){?>
              <a href="javascript:void(0);" data-href='/monitor/updatestatus/<?php echo $list->mid ?>/0' class='forbid'>禁用</a>
              <?php }else{?>
              <a href="javascript:void(0);" data-href='/monitor/updatestatus/<?php echo $list->mid ?>/1' class='open'>启用</a>
              <?php }?>
              <?php echo $this->tag->linkTo(array("monitor/detail/" . $list->mid, "查看")); ?>
              <?php echo $this->tag->linkTo(array("monitor/edit/" . $list->mid, "编辑")); ?>
              <!--?php echo $this->tag->linkTo(array("monitor/delete/" . $list->mid, "删除")); ?-->
              <a href="javascript:void(0);" data-href='/monitor/delete/<?php echo $list->mid ?>' class='delete'>删除</a>
              <?php echo $this->tag->linkTo(array("monitortask/index/" . $list->mid.'?mtstatus=2', "任务列表")); ?>
              </div>
            </td>
          </tr>
    	  <?php } ?>
          </tbody>
          <tbody>
        </table>
        <?php if($page->total_pages > 1){?> 
        <div class="am-cf">
  			<div class="am-fr">
    			<ul class="am-pagination">
    				<li class="am-disabled"><?php echo $page->current, "/", $page->total_pages ?></li>
      				<li><?php echo $this->tag->linkTo("monitor/index?page=1", "首页") ?></li>
      				<li><?php echo $this->tag->linkTo("monitor/index?page=" . $page->before, "上一页") ?></li>
      				<li><?php echo $this->tag->linkTo("monitor/index?page=" . $page->next, "下一页") ?></li>
      				<li><?php echo $this->tag->linkTo("monitor/index?page=" . $page->last, "末页") ?></li>
      				
    			</ul>
  			</div>
		</div>
		<?php }?>
      </div>
    </div>
  </div>
  <!-- content end -->

</div>
<div class="am-modal am-modal-confirm" tabindex="-1" id="my-confirm">
  <div class="am-modal-dialog">
    <div class="am-modal-hd"></div>
    <div class="am-modal-bd">
    </div>
    <div class="am-modal-footer">
      <span class="am-modal-btn" data-am-modal-cancel>取消</span>
      <span class="am-modal-btn" data-am-modal-confirm>确定</span>
    </div>
  </div>
</div>

<div class="am-modal am-modal-no-btn" tabindex="-1" id="doc-modal-1">
    <div class="am-modal-dialog">
        <div class="am-modal-hd" style="color:#fff;background-color:#1f262c;padding-bottom:15px;">
            监控点预览
            <a href="javascript: void(0)" class="am-close am-close-spin" data-am-modal-close style="color:#fff;opacity:1;top:10px">&times;</a>
        </div>
            <iframe id="iframeVideo" frameborder="0" src="" scrolling="auto" style="display: block; width: 100%; height: 100%;"></iframe>
    </div>
</div>
<?php $this->partial("public/footer") ?>
<script type="text/javascript">
$(function() {
  $('.delete').on('click', function() {
      $('.am-modal-hd').html('删除数据');
      $('.am-modal-bd').html('你确定要删除这条记录吗？');
      var deleteHref = $(this).attr("data-href");
      $('#my-confirm').modal({
        relatedTarget: this,
        onConfirm: function(options) {
          window.location.href = deleteHref;
        },
        // closeOnConfirm: false,
        onCancel: function() {
          return false;
        }
      });
    });
  $('.forbid').on('click', function() {
      $('.am-modal-hd').html('禁用监控点');
      $('.am-modal-bd').html('你确定要禁用该监控点吗？');
      var deleteHref = $(this).attr("data-href");
      $('#my-confirm').modal({
        relatedTarget: this,
        onConfirm: function(options) {
          window.location.href = deleteHref;
        },
        // closeOnConfirm: false,
        onCancel: function() {
          return false;
        }
      });
    });
  $('.open').on('click', function() {
      $('.am-modal-hd').html('启用监控点');
      $('.am-modal-bd').html('你确定要启用该监控点吗？');
      var deleteHref = $(this).attr("data-href");
      $('#my-confirm').modal({
        relatedTarget: this,
        onConfirm: function(options) {
          window.location.href = deleteHref;
        },
        // closeOnConfirm: false,
        onCancel: function() {
          return false;
        }
      });
    });

    $("#checked").click(function(){
        var chk_value =[];
        $('input[name="items"]:checked').each(function(){
            chk_value.push($(this).val());
        });
        if(chk_value.length==0){
            alert("你还未选择要操作的项！");
            return;
        }
        $.ajax({
            type:"get",
            url:"/monitor/updatestatusbat/"+chk_value+"/1",
            success:function(result){
                $("input[name='items']").each(function(){
                    if (this.checked) {
                        this.checked = false;
                    }
                });
                window.location.href = '/monitor/index';
            }
        });
    });

    $("#checkeds").click(function(){
        var chk_value =[];
        $('input[name="items"]:checked').each(function(){
            chk_value.push($(this).val());
        });
        if(chk_value.length==0){
            alert("你还未选择要操作的项！");
            return;
        }
        $.ajax({
            type:"get",
            url:"/monitor/updatestatusbat/"+chk_value+"/0",
            success:function(result){
                $("input[name='items']").each(function(){
                    if (this.checked) {
                        this.checked = false;
                    }
                });
                window.location.href = '/monitor/index';
            }
        });
    });

    var openVideo;
    $(".openVideo").click(function(){
        $("#doc-modal-1").find("iframe").attr("src",$(this).attr("data-href"));
    })
    $("#doc-modal-1 .am-close").click(function(){
        $("#doc-modal-1").find("iframe").attr("src","");
    })

});
</script>