<!DOCTYPE html>
<html>
<head lang="en">
  <meta charset="UTF-8">
  
  <title>login </title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="format-detection" content="telephone=no">
  <meta name="renderer" content="webkit">
  <meta http-equiv="Cache-Control" content="no-siteapp" />
  <link rel="alternate icon" type="image/png" href="img/favicon.png">
  <link rel="stylesheet" href="css/amazeui.min.css"/>
  <style>
    .header {
      text-align: center;
    }
    .header h1 {
      font-size: 200%;
      color: #333;
      margin-top: 30px;
    }
    .header p {
      font-size: 14px;
    }
    label {color:FFFFF;}
    body{ background-image: url(""); background-repeat: no-repeat;  background-position: 50% 50%; }
    input{ background-color: transparent; background:none; border:none;}
    
  </style>
</head>
<body>

<div class="header"> 
  <hr />
</div>
<div class="am-g">
  <div class="am-u-lg-6 am-u-md-8 am-u-sm-centered">
	<h3>Login</h3>
    <hr>
    <form  method="post" action="" class="am-form" >

      <label for="email">username:</label>
      <!-- <input type="text" name="username" id="email" value=""> -->
      <?php echo $this->tag->textField(array("username", "size" => "30","style"=>" border:1px solid #DDDDDD; background-color:transparent")) ?>
      <br>
      <label for="password">password:</label>
      <!--  <input type="password" name="pwd" id="password" value="">-->
      <?php echo $this->tag->passwordField(array("password", "size" => "30","style"=>" border:1px solid #DDDDDD; background-color:transparent")) ?>
      <br />
      <div class="am-cf">
        <input type="submit" name="" value="Login" class="am-btn am-btn-primary am-btn-sm am-fl">
      </div>
    </form>
<?php echo $this->getContent(); ?>
    <p>Copyright ..</p>
  </div>
</div>
</body>
</html>
