<?php $this->partial("public/header") ?>
<div class="am-cf admin-main">
  <!-- sidebar start -->
  <?php $this->partial("public/left") ?>
  <!-- sidebar end -->

  <!-- content start -->
  <div class="admin-content">

    <div class="am-cf am-margin">
      <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">编辑摄像头型号</strong></div>
    </div>

	<div class="am-g">
      <div class="am-u-md-6 am-cf">
        <div class="am-fl am-cf">
          <div class="am-btn-toolbar am-fl">
            <div class="am-btn-group am-btn-group-xs">
              <a class="am-btn am-btn-default" href="/cameratype/index"><span class="am-icon-mail-reply"></span> 返回</a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="am-g">
      <div class="am-u-sm-12">
      <?php echo $this->tag->form(["cameratype/save","class"=>"am-form am-form-horizontal lszh-validate"]) ?>
      <?php use Phalcon\Tag; ?>

		<?php echo $this->getContent(); ?>
        
          <table class="am-table am-table-bd am-table-striped admin-content-table">

              <tr>
                  <td width="140">
                      <label for="name">名称</label>
                  </td>
                  <td width="450">
                      <div class="am-form-group">
                      <?php echo $this->tag->textField(array("name", "size" => 50, 'placeholder' => '请输入型号名称',"maxlength"=>"255","minlength"=>"2")) ?>
                      </div>
                  </td>
                  <td><span class="lszh-validate-tip-star">*</span></td>
              </tr>
              <tr>
                  <td width="140">
                      <label for="password">格式</label>
                  </td>
                  <td width="450">
                      <div class="am-form-group">
                      <?php echo $format ?>
                      </div>
                  </td>
                  <td></td>
              </tr>
              <tr>
                  <td width="140">
                      <label for="mainsource">主源地址</label>
                  </td>
                  <td width="450">
                      <div class="am-form-group">
                      <?php echo $this->tag->textField(array("mainsource", "size" => 100, 'placeholder' => '请输入主源地址',"maxlength"=>"255","required"=>"","class"=>"js-pattern-stringUrl","data-validation-message" => "请输入正确的主源地址")) ?>
                      </div>
                  </td>
                  <td><span class="lszh-validate-tip-star">*</span></td>
              </tr>
              <tr>
                  <td width="140">
                      <label for="childsource">子源地址</label>
                  </td>
                  <td width="450">
                      <div class="am-form-group">
                      <?php echo $this->tag->textField(array("childsource", "size" => 100, 'placeholder' => '请输入子源地址',"maxlength"=>"255","class"=>"js-pattern-stringUrl","data-validation-message" => "请输入正确的自源地址")) ?>
                      </div>
                  </td>
                  <td></td>
              </tr>
              <tr>
                  <td width="140">
                      <label for="manufactor">厂商</label>
                  </td>
                  <td width="450">
                      <div class="am-form-group">
                      <?php echo $this->tag->textField(array("manufactor", "size" => 80,"maxlength"=>"500")) ?>
                      </div>
                  </td>
                  <td></td>
              </tr>
              <tr>
                  <td width="140">
                      <label for="tel">电话</label>
                  </td>
                  <td width="450">
                      <div class="am-form-group">
                      <?php echo $this->tag->textField(array("tel", "size" => 30,"class"=>"js-pattern-phone","required"=>"","data-validation-message" => "请输入正确的电话，如：18612121212")) ?>
                      </div>
                  </td>
                  <td><span class="lszh-validate-tip-star">*</span></td>
              </tr>
              <tr>
                  <td width="220">
                      <label for="remark">备注</label>
                  </td>
                  <td width="450">
                      <?php echo $this->tag->textArea(
                          [
                              "remark",
                              "",
                              "cols" => "30",
                              "rows" => 6,
                          ]
                      ) ?>                  </td>
                  <td> </td>
              </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("cid") ?></td>
        <td><?php echo $this->tag->submitButton(["设置","class"=>"am-btn am-btn-primary"]) ?></td>
        <td></td>
    </tr>
</table>
  </form>
      </div>

  </div>
  <!-- content end -->

</div>
<?php $this->partial("public/footer") ?>