<?php $this->partial("public/header") ?>
<div class="am-cf admin-main">
  <!-- sidebar start -->
  <?php $this->partial("public/left") ?>
  <!-- sidebar end -->

  <!-- content start -->
  <div class="admin-content">

    <div class="am-cf am-margin">
      <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">摄像头型号管理</strong></div>
    </div>

	<div class="am-g">
      <div class="am-u-md-9 am-cf">
        <div class="am-fl am-cf">
          <div class="am-btn-toolbar am-fl">
            <div class="am-btn-group am-btn-group-xs">
              <a class="am-btn am-btn-default" href="/cameratype/new"><span class="am-icon-plus"></span> 新增</a>
            </div>
          </div>
        </div>
      </div>
      
      <?php echo $this->tag->form(array("cameratype/index", "autocomplete" => "off")) ?>
      <div class="am-u-md-3 am-cf">
        <div class="am-fr">
          <div class="am-input-group">
          
            <input type="text" class="am-form-field" name="name" placeholder='请输入类型名称'>
                <span class="am-input-group-btn">
                  <input class="am-btn am-btn-default" type="submit" value="搜索">
                </span>
                
          </div>
        </div>
      </div>
      </form>
    </div>

    <div class="am-g">
      <div class="am-u-sm-12">
      <?php use Phalcon\Tag; ?>

		<?php echo $this->getContent(); ?>
        <table class="am-table am-table-bd am-table-striped am-table-compact am-table-hover admin-content-table am-table-bordered">
          <thead>
          <tr>
            <th width="50">ID</th>
            <th width="150">名称</th>
            <th width="80">格式</th>
            <th width="100">厂商</th>
            <th width="180">电话</th>
            <th width="200">创建时间</th>
            <th width="90">状态</th>
            <th width="90">管理</th>
          </tr>
          </thead>
          <tbody>
          <?php foreach ($page->items as $list) { ?>
          <tr>
            <td><?php echo $list->cid ?></td>
            <td><?php echo $list->name ?></td>
            <td><?php
              foreach ($format as $key => $val) {
                if($key == $list->format){
                  echo $val;
                }
              }
              ?></td>
            <td><?php echo $list->manufactor ?></td>
            <td><?php echo $list->tel ?></td>
            <td><?php echo $list->createtime ?></td>
            <td><?php if($list->status == 1)echo '启用';else echo '禁用'; ?></td>
            <td>
              <?php if($list->status == 1)$mm = '禁用';else $mm = '启用'; echo $this->tag->linkTo(array("cameratype/status/" . $list->cid, $mm)); ?>
              <?php echo $this->tag->linkTo(array("cameratype/edit/" . $list->cid, "编辑")); ?>
            </td>
          </tr>
    	  <?php } ?>
          </tbody>
          <tbody>
        </table>
        <?php if($page->total_pages > 1){?> 
        <div class="am-cf">
  			<div class="am-fr">
    			<ul class="am-pagination">
    				<li class="am-disabled"><?php echo $page->current, "/", $page->total_pages ?></li>
      				<li><?php echo $this->tag->linkTo("cameratype/index?page=1", "首页") ?></li>
      				<li><?php echo $this->tag->linkTo("cameratype/index?page=" . $page->before, "上一页") ?></li>
      				<li><?php echo $this->tag->linkTo("cameratype/index?page=" . $page->next, "下一页") ?></li>
      				<li><?php echo $this->tag->linkTo("cameratype/index?page=" . $page->last, "末页") ?></li>
      				
    			</ul>
  			</div>
		</div>
		<?php }?>
      </div>
    </div>
  </div>
  <!-- content end -->

</div>
<?php $this->partial("public/footer") ?>